FROM dunglas/frankenphp:php8.3-bookworm

WORKDIR /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction \
    --prefer-dist

RUN php artisan optimize

EXPOSE 80

CMD ["frankenphp", "php-server", "-r", "public/"]
